version: "3.9"

services:
  app:
    build:
      context: .
    container_name: mondo-text-app
    environment:
      PG_HOST: quriousri_postgres in docker-compose
      PG_PORT: 5432
      PG_DATABASE: quriousri_db
      PG_USER: postgres
      PG_PASSWORD: postgres
    command: ["mondo_ingest", "--config", "/app/config.json"]
    volumes:
      - mondo_cache:/app/temp/mondo_cache
    networks:
      - quriousri_quriousri-network

volumes:
  mondo_cache:

networks:
  quriousri_quriousri-network:
    external: true